apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-platform-config
  namespace: billing
data:
  DB_HOST: postgres.billing.svc.cluster.local
  DB_NAME: billing
  REDIS_HOST: redis.billing.svc.cluster.local
  KAFKA_BOOTSTRAP: kafka.billing.svc.cluster.local:9092
  PG_BASE_URL: https://pg.example.com
  OAUTH_ISSUER_URI: https://auth.example.com/realms/billing
  OTEL_EXPORTER_OTLP_ENDPOINT: http://tempo.observability.svc.cluster.local:4318
  OTEL_SERVICE_NAME: billing-platform
