apiVersion: v1
kind: Namespace
metadata:
  name: wallet
  labels:
    app.kubernetes.io/name: wallet-platform
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
