-- V1: Wallet Platform 초기 스키마.
-- 도메인: Wallet (잔액) / Order (주문) / Payment (결제) / Refund (환불) / Ledger (원장) / Outbox / Idempotency

-- ────────────────────────────────────────────────────────
-- WALLETS — owner 별 잔액 (낙관적 락)
-- ────────────────────────────────────────────────────────
CREATE TABLE wallets (
    id              UUID         PRIMARY KEY,
    owner_id        VARCHAR(128) NOT NULL UNIQUE,
    currency        VARCHAR(3)   NOT NULL,
    balance         DECIMAL(19, 4) NOT NULL DEFAULT 0,
    blocked         DECIMAL(19, 4) NOT NULL DEFAULT 0,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    version         BIGINT       NOT NULL,
    CONSTRAINT chk_wallet_balance_nonneg CHECK (balance >= 0),
    CONSTRAINT chk_wallet_blocked_nonneg CHECK (blocked >= 0),
    CONSTRAINT chk_wallet_blocked_le_balance CHECK (blocked <= balance)
);

-- ────────────────────────────────────────────────────────
-- ORDERS — 주문 + 상태머신 (CREATED → PAID → REFUNDED, CREATED → CANCELLED)
-- ────────────────────────────────────────────────────────
CREATE TABLE orders (
    id              UUID         PRIMARY KEY,
    buyer_id        VARCHAR(128) NOT NULL,
    total_amount    DECIMAL(19, 4) NOT NULL,
    currency        VARCHAR(3)   NOT NULL,
    status          VARCHAR(32)  NOT NULL,
    payment_id      UUID,
    refund_id       UUID,
    created_at      TIMESTAMP    NOT NULL,
    updated_at      TIMESTAMP    NOT NULL,
    version         BIGINT       NOT NULL
);

CREATE INDEX idx_orders_buyer_created ON orders (buyer_id, created_at);
CREATE INDEX idx_orders_status        ON orders (status);

CREATE TABLE order_items (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        UUID         NOT NULL,
    sku             VARCHAR(128) NOT NULL,
    quantity        INT          NOT NULL,
    unit_price      DECIMAL(19, 4) NOT NULL,
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders (id) ON DELETE CASCADE
);

CREATE INDEX idx_order_items_order ON order_items (order_id);

-- ────────────────────────────────────────────────────────
-- PAYMENTS — PG 결제. PG 트랜잭션 ID 매핑 + 멱등성 키.
-- ────────────────────────────────────────────────────────
CREATE TABLE payments (
    id                  UUID         PRIMARY KEY,
    order_id            UUID         NOT NULL,
    amount              DECIMAL(19, 4) NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    method              VARCHAR(32)  NOT NULL,         -- CARD, BANK_TRANSFER, WALLET
    status              VARCHAR(32)  NOT NULL,         -- PENDING, APPROVED, FAILED
    pg_transaction_id   VARCHAR(256),
    idempotency_key     VARCHAR(128) NOT NULL UNIQUE,
    error_code          VARCHAR(64),
    error_message       VARCHAR(2048),
    created_at          TIMESTAMP    NOT NULL,
    updated_at          TIMESTAMP    NOT NULL,
    version             BIGINT       NOT NULL,
    CONSTRAINT fk_payments_order FOREIGN KEY (order_id) REFERENCES orders (id)
);

CREATE INDEX idx_payments_order  ON payments (order_id);
CREATE INDEX idx_payments_status ON payments (status);

-- ────────────────────────────────────────────────────────
-- REFUNDS — 환불 요청 + 처리 결과
-- ────────────────────────────────────────────────────────
CREATE TABLE refunds (
    id                  UUID         PRIMARY KEY,
    payment_id          UUID         NOT NULL,
    amount              DECIMAL(19, 4) NOT NULL,
    currency            VARCHAR(3)   NOT NULL,
    reason              VARCHAR(512),
    status              VARCHAR(32)  NOT NULL,         -- REQUESTED, APPROVED, COMPLETED, FAILED
    pg_refund_id        VARCHAR(256),
    requested_at        TIMESTAMP    NOT NULL,
    completed_at        TIMESTAMP,
    version             BIGINT       NOT NULL,
    CONSTRAINT fk_refunds_payment FOREIGN KEY (payment_id) REFERENCES payments (id)
);

CREATE INDEX idx_refunds_payment ON refunds (payment_id);

-- ────────────────────────────────────────────────────────
-- LEDGER — append-only 거래 원장. Wallet 잔액의 진실 (재구성 가능).
-- ────────────────────────────────────────────────────────
CREATE TABLE ledger_entries (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    wallet_id       UUID         NOT NULL,
    entry_type      VARCHAR(32)  NOT NULL,             -- DEPOSIT, WITHDRAWAL, BLOCK, UNBLOCK, REFUND, ADJUSTMENT
    amount          DECIMAL(19, 4) NOT NULL,           -- signed: + = credit, - = debit
    balance_after   DECIMAL(19, 4) NOT NULL,
    reference_type  VARCHAR(32),                        -- ORDER, PAYMENT, REFUND, ADJUSTMENT
    reference_id    VARCHAR(128),
    trace_id        VARCHAR(64),
    occurred_at     TIMESTAMP    NOT NULL,
    CONSTRAINT fk_ledger_wallet FOREIGN KEY (wallet_id) REFERENCES wallets (id)
);

CREATE INDEX idx_ledger_wallet_occurred ON ledger_entries (wallet_id, occurred_at);
CREATE INDEX idx_ledger_reference       ON ledger_entries (reference_type, reference_id);

-- ────────────────────────────────────────────────────────
-- OUTBOX — 트랜잭션 안전 이벤트 발행 (Outbox Pattern)
-- ────────────────────────────────────────────────────────
CREATE TABLE outbox (
    id              UUID         PRIMARY KEY,
    aggregate_type  VARCHAR(64)  NOT NULL,
    aggregate_id    VARCHAR(128) NOT NULL,
    event_type      VARCHAR(64)  NOT NULL,
    payload         CLOB         NOT NULL,
    created_at      TIMESTAMP    NOT NULL,
    published_at    TIMESTAMP
);

CREATE INDEX idx_outbox_unpublished ON outbox (published_at, created_at);

-- ────────────────────────────────────────────────────────
-- IDEMPOTENCY_KEYS — 클라이언트 재시도 안전 (Redis NX 와 별도 — DB 기준 영구 보존)
-- ────────────────────────────────────────────────────────
CREATE TABLE idempotency_keys (
    key_value       VARCHAR(128) PRIMARY KEY,
    request_hash    VARCHAR(128) NOT NULL,
    response_status INT,
    response_body   CLOB,
    created_at      TIMESTAMP    NOT NULL,
    expires_at      TIMESTAMP    NOT NULL
);

CREATE INDEX idx_idempotency_expires ON idempotency_keys (expires_at);

-- ────────────────────────────────────────────────────────
-- DLQ_REPLAY — DLQ 재처리 이력
-- ────────────────────────────────────────────────────────
CREATE TABLE dlq_replay_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic           VARCHAR(128) NOT NULL,
    original_offset BIGINT,
    payload         CLOB,
    failure_reason  VARCHAR(2048),
    replayed_at     TIMESTAMP    NOT NULL,
    replayed_by     VARCHAR(128) NOT NULL
);
